[package]
name = "dreas-hsm-client"
version = "0.1.0"
edition = "2025"
description = "Rust client for secure Grok LLM API calls with HSM integration"
authors = ["kirankbee@gmail.com"]
license = "MIT OR Apache-2.0"

[dependencies]
reqwest = { version = "0.12", features = ["json", "rustls-tls"] } # HTTP client for Grok API
serde = { version = "1.0", features = ["derive"] }              # Serialization/deserialization
serde_json = "1.0"                                             # JSON handling for API payloads
ring = "0.17"                                                  # Cryptographic operations (AES-GCM, signing)
pkcs11 = "0.5"                                                 # PKCS#11 bindings for HSM
tracing = "0.1"                                                # Observability for governance
tracing-subscriber = { version = "0.3", features = ["env-filter"] } # Logging configuration
tokio = { version = "1.40", features = ["full"] }              # Async runtime
anyhow = "1.0"                                                 # Error handling

[dev-dependencies]
mockito = "1.5"                                                # Mock server for testing API calls