# DREAS Configuration File
# DeepRockEncryptionAsService - Enterprise-Grade Agentic AI Security Framework
# 
# Author: Kiran Kumar Balijepalli
# Date: 2024-12-19

[gcp]
project_id = "your-project-id"
kms_key_uri = "projects/your-project/locations/us-central1/keyRings/dreas-keyring/cryptoKeys/dreas-key/cryptoKeyVersions/1"
location = "us-central1"
service_account_key_path = "/path/to/service-account-key.json"

[security]
enable_audit_logging = true
enable_key_escrow = true
audit_log_retention_days = 365
minimum_escrow_signatures = 2

[api]
port = 8080
host = "0.0.0.0"
enable_cors = true
rate_limit_requests_per_minute = 1000

[logging]
level = "info"
format = "json"
enable_structured_logging = true

[storage]
gcs_bucket = "dreas-storage-bucket"
bigquery_dataset = "dreas_audit_logs"
enable_cmek_encryption = true

[models]
default_model = "gpt-4"
max_tokens = 4096
temperature = 0.7
timeout_seconds = 30

[monitoring]
enable_health_checks = true
health_check_interval_seconds = 60
metrics_retention_hours = 168  # 7 days
alert_webhook_url = "https://your-webhook-url.com/alerts"
